### ISSUE TITLE
Command: MyTime

### ISSUE THREAD

**Issue by Wolftousen** [liatrio/timebot#13]
Setup a command for the Slack bot to respond to.

This command should respond to the term `@timebot mytime q[1-4][yy]`

```[tasklist]
### Tasks
- [x] Determine our Harvest User Id based on our Slack information (probably name or email)
- [x] Get all of our time entries from the quarter requested or the current quarter if the request is empty
- [x] Sum up time spent in each category: billable, utilization, collaboration, PTO, % toward utilization target
- [x] Get Project names from Harvest for each category having a Sum > 0
- [x] Return a table formated message to the user with the information
```

* Quarters are yearly quarters currently, but should be configurable

Example command over in [Gratibot](https://github.com/liatrio/gratibot/blob/main/features/balance.js).  They call it features over there, let's call it commands here
