### ISSUE TITLE
Command: ProjectTime

### ISSUE THREAD

**Issue by Wolftousen** [liatrio/timebot#14]
Setup a command for the Slack bot to respond to.

This command should respond to the term `@timebot projtime [project name]`

```[tasklist]
### Tasks
- [x] Determine our Harvest User Id based on our Slack information (probably name or email)
- [x] Look up the project id for the project by name
- [x] Get all the time entries for that project
- [x] If the User calling is participating in the project Sum up their hours on it
- [x] If the User calling is a project admin Sum up all hours for each participant
- [x] Sum total hours spent by everyone on the project
- [x] Return a table formatted message to the user with the information
```

Example command over in [Gratibot](https://github.com/liatrio/gratibot/blob/main/features/balance.js).  They call it features over there, let's call it commands here
